---
apiVersion: v2
appVersion: version-v6.3.0
description: Calibre is a powerful and easy to use e-book manager.
name: calibre
version: 6.0.1
kubeVersion: ">=1.16.0-0"
keywords:
  - calibre
home: https://github.com/k8s-at-home/charts/tree/master/charts/stable/calibre
icon: https://github.com/kovidgoyal/calibre/raw/master/resources/images/lt.png
sources:
  - https://hub.docker.com/r/linuxserver/calibre/
  - https://github.com/kovidgoyal/calibre/
maintainers:
  - name: rolfberkenbosch
    email: rolf@berkenbosch.nl
dependencies:
  - name: common
    repository: https://rumblpak.github.io/helm-charts
    version: 0.1.1
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded common to `0.1.1`.
