---
apiVersion: v2
appVersion: "4.3"
description: Self-hosted YouTube downloader built on Material Design
name: youtubedl-material
version: 4.4.4
kubeVersion: ">=1.16.0-0"
keywords:
  - youtubedl-material
home: https://github.com/k8s-at-home/charts/tree/master/charts/stable/youtubedl-material
icon: https://i.imgur.com/IKOlr0N.png
sources:
  - https://github.com/Tzahi12345/YoutubeDL-Material
  - https://github.com/k8s-at-home/charts/tree/master/charts/youtubedl-material
maintainers:
  - name: Patricol
    url: https://patricol.co/
dependencies:
  - name: common
    repository: https://rumblpak.github.io/helm-charts
    version: 0.1.1
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` to version `0.1.1`. 
