---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: app-template
    repo: https://rumblpak.github.io/helm-charts/
    # this example is not automatically updated, so be sure to use the latest chart version
    version: 0.1.1
    releaseName: &releaseName vaultwarden
    namespace: &releaseNamespace default
    valuesFile: values.yaml
commonAnnotations:
  meta.helm.sh/release-name: *releaseName
  meta.helm.sh/release-namespace: *releaseNamespace
commonLabels:
  app.kubernetes.io/managed-by: Helm
